### ISSUE TITLE
need UI for triggering replication to USB drive

### ISSUE THREAD

**Issue by mcplanner** [digidem/ecuador-map-editor#6]

**Comment by substack** [comment]
There is a very bare-bones form in `public/replicate.html`. Users type in the path they want to replicate to on the local file system.

**Comment by mcplanner** [comment]
Nice.

It would be easier for people to respond to popup question (something that comes to them, rather than something they have to seek). Is there something like a standard system alert we can use?

If so, are there any necessary messages beyond these (translation and final wording TBD)?
- USB device detected. Copy files to local drive? (options: yes, cancel)
- Select a destination (options: folder selector)
- Download complete. Eject? (options: eject drive, cancel)

**Comment by gmaclennan** [comment]
@substack what are your thoughts about auto detection of a USB drive? Can we fire a UI event when a drive is inserted with the DB on it? If not the workflow would be selecting the file on the drive.

@mcplanner Electron (what we use to wrap this web app as a desktop app) implements a standard system dialog for selecting a file or folder. We can have a button that opens that dialog.

Not sure that we can eject USB drives from within the app. I suspect that is something the user will have to do via the operating system, the same way you would eject any USB drive.

@mcplanner the main thing here is thinking through language that makes sense to the user. I can help with translation.

**Comment by mcplanner** [comment]
Yes on language. Can you confirm those are all the actions we need to
communicate, before we commence wordsmithing? For example, I wasn't sure
about the USB eject, thanks for flagging it.

On Mon, Feb 29, 2016 at 12:43 PM, Gregor MacLennan <notifications@github.com

**Comment by mcplanner** [comment]
@substack What happens if an external drive is disconnected before the sync completes? Would it leave half-synced files on the external drive or the local drive need to be dealt with?

**Comment by mcplanner** [comment]
@gmaclennan What distinct states are there beyond these? Are these all possible?

- user inserts a drive that contains a valid sync folder 
- user selects a folder that is not recognizable as a sync folder
- user inserts a drive that is blank, or otherwise does not contain a valid sync folder
- user inserts a drive that does not have enough available space to sync the user's local files
- user has initiated the replicate/sync process, but would like to cancel without selecting a folder and return to the primary interface
- user would like to interrupt and cancel the sync process before completion

I'm mocking these up, but would appreciate being told if there are more by the end of the week.

**Comment by mcplanner** [comment]
Here are mockups for the core functions. Happy to discuss, as always.

1) The main screen, with sync button.
2) The initial prompt. If the user selects "Sync" the process starts and goes to 3 or the appropriate error (6 ,7, 8). "Cancel" closes the window.
3) In progress. This assures the user something is happening, especially if it's
[ecuador_map_prototype_150302.pdf](https://github.com/digidem/ecuador-map-editor/files/155479/ecuador_map_prototype_150302.pdf)
 going to take a while. If it works, it automatically goes to 4. Depending on the failure mode, it can go to 6, 7, or 8.
4) Successful sync. "Close" closes the window.
5) Cancelled. The user has cancelled the sync, but can select a new folder and try again. "Sync" functions here as in 2. "Cancel" closes the window.
6) Insufficient space. The external drive does not have enough space to complete the transfer. "Close" closes the window.
7) No sync folder detected. Confirm the user wants to create a new one. "Create and Sync" works as in 2. "Cancel" closes the window.
8) Invalid folder selected. Prompt the user to try again. "Sync" functions here as in 2. "Cancel" closes the window.
9) Sync interrupted. For example, the destination drive is disconnected abruptly. "Close" closes the window.

**Comment by gmaclennan** [comment]
Thanks Ruth.

How would the user Cancel to reach (5)? I don't think it's needed, since "Cancel" always closes the window.

In (2) the "Sync" button should be disabled, since we don't have anything to sync with.

I don't think we should show the cancel button in (3) while syncing is in progress, let's not give the user that option.

(8) and (9) are pretty much the same: There was some kind of error during syncing. I think the buttons should be the same.

User flow is:

1. Starts sync process by clicking "Sync" button on main window --> Modal appears with "Sync" button deactivated. At any time clicking cancel just closes the window.
2. Selects a folder. 3 potential outcomes:
    1. Folder is empty --> show message, activate Sync button and change text to "Create & Sync"
    2. Folder is non-empty but not a database (i.e. the user has selected a folder with other data) --> show an error message, "Sync" button remains disabled. --> User selects a different folder or cancels
    3. Folder is valid --> Start sync, remove buttons, show a message / image to show something is happening.
3. User clicks "Sync" or "Create & Sync". 2 outcomes:
    1. Sync was successful --> show message and show "Close" button.
    2. Sync was unsuccessful --> show message and go back to 2.

**Comment by mcplanner** [comment]
Cancel and Close are technically distinct. The user could click a folder,
realize it's the wrong one, and want to try again quickly. That's a case
for Cancel. Close ends the whole sequence.

The Sync button should be visible when they first open the window to assure
them they're in the right place. If they don't select a folder, it should
give them (8, invalid folder selection).

If there's already a chance the user could abruptly end the sync
(unplugging something), it's not like removing the Cancel button on 3 will
prevent syncs from being interrupted. It's more reassuring to have the
button there, since it is technically possible with or without it.

(8) and (9) are distinct. If something comes uplugged in (9), that's useful
information for the user.

I'm unclear how (7) and (8) are distinct. What would it look like to select
a folder that doesn't have a database? Wouldn't it always go with (7),
prompting the user to create one? That makes (8) feel unnecessary.

**Comment by substack** [comment]
> @substack What happens if an external drive is disconnected before the sync completes? Would it leave half-synced files on the external drive or the local drive need to be dealt with?

The local database will be fine, but the external drive may need to be synced again. I don't think the data can get corrupted, only incomplete, but I could be wrong about that. LevelDB ought to be good about recovering gracefully from the process being destroyed or the system losing power, and that is not too dissimilar from a device disconnecting before the write cache has been fully written.

> @substack what are your thoughts about auto detection of a USB drive? Can we fire a UI event when a drive is inserted with the DB on it? If not the workflow would be selecting the file on the drive.

This should be possible, I just don't know how to subscribe to device mount/unmount events in a cross-platform way.

**Comment by mcplanner** [comment]
Thanks for clarifying. Maybe something to figure out in a version round.

**Comment by gmaclennan** [comment]
> This should be possible, I just don't know how to subscribe to device mount/unmount events in a cross-platform way.

This would be the way: https://github.com/MadLittleMods/node-usb-detection

But we will need to compile separately on each platform: https://github.com/electron-userland/electron-packager/issues/215

Or prebuild that module for Windows.

Might have to deal with this anyway since we use leveldown, which is a native module, although there do seem to be prebuilt versions of that too.

I suggest leaving USB detection for now and revisiting later. Obviously it would make the user experience much nicer.

**Comment by gmaclennan** [comment]
@mcplanner can you share the latest mockups? James are you able to at least throw together a folder selection dialog by this Sunday, and a way to cancel (you can't get out the Replicate screen right now once you're in it), since entering a file path is complicated and prone to error.

For people to be able to continue to work on this after I leave we need the UI that Ruth has prepared, that can show errors, progress, etc.

**Comment by mcplanner** [comment]
I take that to mean you sign off on the designs I sent you a while back.
[ecuador_map_prototype160311.pdf](https://github.com/digidem/ecuador-map-editor/files/169657/ecuador_map_prototype160311.pdf)

**Comment by gmaclennan** [comment]
@substack working with this today I have seen that this synchronization step is a really critical part of the workflow that has the potential to confuse users and cause errors. I think we need the following logic implemented:

1. Prior to replication:
  - Have a way to cancel from the replication page and return to the map without replicating.

2. Checks on the folder selected:
  - non-empty but not a leveldb (e.g. other files) --> show error
  - is it empty or a valid leveldb / hyperlog --> go ahead with sync

3. During replication:
  - disable button so the user can't double click and start two simultaneous replications (results in error). 
  - give indication of progress - we've found replication can be quite slow, especially after entering large polylines.

Time is likely too short to implement the full UI that Ruth suggests, although that would be good, but at the least we need these checks/UI in place so that I can leave this package with the Waorani for them to continue entering data and syncing.
